# Generated by Django 6.0.4 on 2026-05-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_csvupload'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adgroup',
            index=models.Index(fields=['name'], name='core_adgrou_name_baee54_idx'),
        ),
        migrations.AddIndex(
            model_name='adgroup',
            index=models.Index(fields=['campaign'], name='core_adgrou_campaig_97400e_idx'),
        ),
        migrations.AddIndex(
            model_name='advertiser',
            index=models.Index(fields=['name'], name='core_advert_name_877704_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['name'], name='core_campai_name_adaf38_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['advertiser'], name='core_campai_adverti_aacf88_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date'], name='core_campai_start_d_2ceeab_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['end_date'], name='core_campai_end_dat_17e6fd_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereport',
            index=models.Index(fields=['date'], name='core_perfor_date_c91fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereport',
            index=models.Index(fields=['adgroup'], name='core_perfor_adgroup_587c6a_idx'),
        ),
    ]
